name: poetry application

on:
  push:
    branches: [master]
  pull_request:

jobs:
  env:
    POETRY_ROOT_PATH: fortune-cookie-factory
  strategy:
    fail-fast: false
    matrix:
      python-version: [3.9]
      poetry-version: [1.3.1]
      os: [ubuntu-latest]
  
  unit-test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          cd $POETRY_ROOT_PATH
          poetry install
      - name: Run tests
        run: |
          cd $POETRY_ROOT_PATH
          poetry run pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  security-test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          cd $POETRY_ROOT_PATH
          poetry install
      - name: Run security check
        run: |
          cd $POETRY_ROOT_PATH
          poetry run bandit fortune_cookie
          poetry run safety check